Prevent install on Big Sur (broken)

diff --git a/support/install-from-closure.sh.in b/support/install-from-closure.sh.in
--- a/support/install-from-closure.sh.in
+++ b/support/install-from-closure.sh.in
@@ -19,8 +19,9 @@ if [ "$(uname -s)" != "Darwin" ]; then
     exit 1
 fi
 
-if [ "$(sw_vers -productVersion | cut -d "." -f 2)" -lt 14 ]; then
-    echo "error: this script requires macOS 10.14 or higher" >&2
+macos_version="$(sw_vers -productVersion | cut -d "." -f 1,2)"
+if [ "${macos_version}" != "10.14" -a "${macos_version}" != "10.15" ]; then
+    echo "error: this script requires macOS 10.14 or 10.15" >&2
     exit 1
 fi
 
